### ISSUE TITLE
files in lists

### ISSUE THREAD

**Issue by Fuuu12** [sallymmx/m2clip#2]
Can you share wher can i find the files in /list?
I found thar you have provided k400_train.txt and k400_val.txt (but i also find that the label to the video is not true when i compare them to official csv files)
where can i find kinetics_400_labels.csv and k400_mlm_lables.txt?

**Comment by Larie-hmz** [comment]
I also want two files. Have you made any progress？

**Comment by sallymmx** [comment]
uploaded now.
