### ISSUE TITLE
lists/k400_mlm_lables.txt能否提供

### ISSUE THREAD

**Issue by zz-2024** [sallymmx/m2clip#3]
您好，该文档的作用能否进行简要介绍，并提供该txt文件。
非常感谢您！

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by Larie-hmz** [comment]
您好，我也需要lists/k400_mlm_lables.txt和lists/kinetics_400_labels.csv这两个文件，请问能否该对文档的作用进行简要介绍，并提供该txt和csv文件。
非常感谢~

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by Fuuu12** [comment]
> 您好，我也需要lists/k400_mlm_lables.txt和lists/kinetics_400_labels.csv这两个文件，请问能否该对文档的作用进行简要介绍，并提供该txt和csv文件。 非常感谢~

您好！请问您有收到这个文件或者处理方法吗？

**Comment by Larie-hmz** [comment]
> > 您好，我也需要lists/k400_mlm_lables.txt和lists/kinetics_400_labels.csv这两个文件，请问能否该对文档的作用进行简要介绍，并提供该txt和csv文件。 非常感谢~
> 
> 您好！请问您有收到这个文件或者处理方法吗？

https://github.com/sallymmx/m2clip/issues/4#issuecomment-2297900124 在这个issue中有提到处理的方法，但我还没有试验，您可以尝试一下看看是否可行~ 有新进展再继续交流~

**Comment by kinder666** [comment]
您好，我也需要lists/k400_mlm_lables.txt和lists/kinetics_400_labels.csv这两个文件，请问能否该对文档的作用进行简要介绍，并提供该txt和csv文件。 非常感谢~

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by ghost233lism** [comment]
您好，我也需要lists/k400_mlm_lables.txt和lists/kinetics_400_labels.csv这两个文件，请问能否该对文档的作用进行简要介绍，并提供该txt和csv文件。 非常感谢~

**Comment by liyapeng-Y** [comment]
您好，我想请问下能不能提供下lists/k400_mlm_lables.txt这个文件或者其介绍，十分感谢

**Comment by sallymmx** [comment]
uploaded now.

**Comment by Liu-arch** [comment]
麻烦问一下，mlm_label 到底是怎么构建的

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by WeiWeiqaq** [comment]
您好，请问能否对lists/k400_mlm_lables.txt文档的作用进行简要介绍，是怎么构造出来的？ 非常感谢~
