### ISSUE TITLE
关于lists/k400_mlm_lables.txt

### ISSUE THREAD

**Issue by xiaobei1011** [sallymmx/m2clip#4]
您好，您的代码非常的清晰明了，对我提供了很大的帮助。关于lists/k400_mlm_lables.txt这个文件，请问它的作用是什么，能否提供一下该文档呢？

**Comment by zz-2024** [comment]
我也遇到了同样的问题，如有进展，希望能和您同步

**Comment by Larie-hmz** [comment]
您好，我也需要lists/k400_mlm_lables.txt和lists/kinetics_400_labels.csv这两个文件。
如有进展希望一起分享，非常感谢~

**Comment by zz-2024** [comment]
我使用了bert uncased_L-2_H-128_A-2.zip中的词表，猜测：

--mlm_label 'lists/vocab.txt'是词表，

--label_txt '/home/jiayi.chen/projects/mmaction2/tools/data/kinetics/label_map_k400.txt'是类别名的列表

**Comment by zz-2024** [comment]
我使用了bert uncased_L-2_H-128_A-2.zip中的词表，猜测：

--mlm_label 'lists/vocab.txt'是词表，

--label_txt 'data/kinetics/label_map_k400.txt'是类别名的列表

**Comment by sallymmx** [comment]
uploaded now.
