### ISSUE TITLE
Tunable Param为什么是16

### ISSUE THREAD

**Issue by zz-2024** [sallymmx/m2clip#5]
您好，我看了论文中的图表：
![image](https://github.com/user-attachments/assets/c10efc2c-7101-4c76-8d2b-9bf25fbd304a)

显示m2-clip的Tunable Param为16，但是我运行scripts/train_k400_clip_vit_b16_adapter12x384.sh，结果是："n_trainable_params": 31529162（31.53M）, "n_total_params": 184302283（184.30M ）。

**Comment by sallymmx** [comment]
For K400 please use model: clip_vit_base_patch16_multimodal_adapter12x384
For SSV2 please use model: clip_vit_base_patch16_multimodal_adapter24x384
