### ISSUE TITLE
lists/k400_mlm_lables.txt能否提供

### ISSUE THREAD

**Issue by tamakoko** [sallymmx/m2clip#7]
在实现过程中发现缺少了这部分文件和csv文件，这些文件能否提供学习呢？

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by tamakoko** [comment]
您好，请问能否提供这个文件或者告知一下这个文件的组织方式呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sallymmx/m2clip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sallymmx/m2clip] lists/k400_mlm_lables.txt能否提供 (Issue #7)





 您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by sallymmx** [comment]
您好，我是王蒙蒙，您的邮件我已收到，并及时回复。

**Comment by sallymmx** [comment]
https://github.com/sallymmx/m2clip/blob/master/k400_mlm_lables.txt
