### ISSUE TITLE
MLM_LABEL_PATH = '/mnt/f/1234/zuhui/m2clip-master/mlm_labels.txt'

### ISSUE THREAD

**Issue by xiguaxiguaxigua** [sallymmx/m2clip#9]
Hello,

Can you please give me the '/mnt/f/1234/zuhui/m2clip-master/mlm_labels.txt' file ?
My email is 'zjq@sxit.edu.cu'
Thank you very much.

**Comment by sallymmx** [comment]
uploaded now.
